---

#############################################
##                Metier                   ##
##                                         ##
#############################################

## Packages placés dans Médusa nécéssaire pour l'architecture TRAX 
## REPMGR

repmgr_package: "repmgr_17-5.5.0-1PGDG.rhel8.x86_64.rpm"
repmgr_file_path: "{{ identifiant_zp_repo }}-generic/repmgr/{{ repmgr_package }}"

## Définition des groupes de volumes logiques (Volume Groups) pour les vm bases de données LV_PGSQL
lvm_volume_groups:
  - vg: 'VG_DATA'
    pvs: ['/dev/sdb']
    logical_volumes:
      - lv: LV_PGSQL
        size: 100%VG
        mount: '/var/lib/pgsql'
        mount_state: 'mounted'
        state: 'present'
        fs_type: 'xfs'
