#####################################################################
#            Variables tenant observability                         #
#####################################################################

obs_service: heartbeat
obs_role: heartbeat
