---

#############################################
##                Metier                   ##
##                                         ##
#############################################

## Packages placés dans Médusa nécéssaire pour l'architecture TRAX 
## PORTAILXAPI BDD
portailxapi_bdd: "portailxapi_pg.dump"
portailxapi_bdd_path: "{{ identifiant_zp_repo }}-generic/portailxapi/{{ portailxapi_bdd }}"

#############################################
##               RUCHE                     ##
##                                         ##
#############################################

postgresql_unix_account_password: "{{ postgresql_unix_account_password }}"
postgresql_db_account_password: "{{ postgresql_db_account_password }}"
postgresql_version: 17.6
postgresql_listen_addresses: "*"
postgres_path_data: "/var/lib/pgsql/17"
postgresql_ssl_enable: false

postgresql_configuration:
  wal_level: replica
  max_wal_senders: 10
  hot_standby: "on"
  max_replication_slots: 10
  archive_mode: "on"
  archive_command: '/bin/true'
  listen_addresses: '*'

#####################################################################
#        Variables créations BDD TRAX et REPMGR et portailxapi      #
#####################################################################

postgresql_databases:
  - name: "{{ postgres_bdd_trax }}"
    owner: dbotrax3
    encoding: UTF8
    schemas:
      - name: public
  - name: "{{ postgres_bdd_repmgr }}"
    owner: repl
    encoding: UTF8
    schemas:
      - name: public
  - name: "{{ postgres_bdd_portailxapi }}"
    owner: "{{ postgres_user_portailxapi }}"
    encoding: UTF8
    schemas:
      - name: public

#####################################################################
#   Variables créations USERS dbotrax3 et repl et portailxapi       #
#####################################################################

postgresql_roles:
# Création de l'utilisateur dbotrax3
  - name: "{{ postgres_user_trax }}"
    password: "{{ traxbdd_user_password }}"
    hosts_allow:
      - ip: "{{ hostvars[groups['loadbalancer'][0]].ansible_default_ipv4.address }}"
        prefix: 32
    flags: LOGIN,REPLICATION,SUPERUSER,CREATEDB,CREATEROLE
    databases:
      - name: "{{ postgres_bdd_trax }}"
        privs:
          - all@public
        privsSchema:
          - usage@public
          - create@public
# Création de l'utilisateur repl
  - name: "{{ postgres_user_repmgr }}"
    password: "{{ repmgr_user_password }}"
    hosts_allow:
      - ip: "{{ hostvars[groups['loadbalancer'][0]].ansible_default_ipv4.address }}"
        prefix: 32
    flags: SUPERUSER
    databases:
      - name: "{{ postgres_bdd_repmgr }}"
        privs:
          - all@public
        privsSchema:
          - usage@public
          - create@public
# Création de l'utilisateur dboportailxapi
  - name: "{{ postgres_user_portailxapi }}"
    password: "{{ portailxapi_bd_password }}"
    hosts_allow:
      - ip: "{{ hostvars[groups['loadbalancer'][0]].ansible_default_ipv4.address }}"
        prefix: 32
    flags: LOGIN,REPLICATION,SUPERUSER,CREATEDB,CREATEROLE
    databases:
      - name: "{{ postgres_bdd_portailxapi }}"
        privs:
          - all@public
        privsSchema:
          - usage@public
          - create@public

#####################################################################
#            Variables tenant observability                         #
#####################################################################

db_port: "5432"
obs_service: postgresql-17
obs_role: postgresql_primary
obs_beats_modules:
  - templates/supervision/filebeat/postgresql.yml
  - templates/supervision/metricbeat/postgresql.yml

## Ouverture des ports nécessaires pour le groupe database
firewalld:
  - name: "Ouverture du port 80"
    port: "80/tcp"
    permanent: true
    immediate: true
    zone: "public"

  - name: "Ouverture du port 443"
    port: "443/tcp"
    permanent: true
    immediate: true
    zone: "public"

  - name: "Ouverture du port 5432"
    port: "5432/tcp"
    permanent: true
    immediate: true
    zone: "public"

  - name: "Ouverture du port 9200"
    port: "9200/tcp"
    permanent: true
    immediate: true
    zone: "public"
