- name: Récupération du fichier portailxapi_files.tar.gz et dépôt sur la VM
  minarm.core.adaptable.get_url:
    url: "atf://{{ portailxapi_file_path }}"
    dest: "{{ vm_file_path }}"
    url_category: "livrable"
    username: "{{ artifactory_user }}"
    password: "{{ artifactory_password }}"

- name: Vérifier et vider le répertoire /Data/www/portailxapi
  file:
    path: "{{ apache_www_path }}"
    state: absent

- name: Recréer le répertoire vide /Data/www/portailxapi
  file:
    path: "{{ apache_www_path }}"
    state: directory
    owner: apache
    group: apache
    mode: '0755'

- name: Extraction de portailxapi
  unarchive:
    src: /tmp/{{ portailxapi_package }}
    dest: "/Data/www/"
    remote_src: true

- name: Permissions 0775 des répertoires portailxapi
  file:
    path: "{{ apache_www_path }}"
    state: directory
    mode: '0775'
    recurse: true

- name: Liste fichiers portailxapi
  find:
    paths: "{{ apache_www_path }}"
    file_type: file
  register: files_to_chmod

- name: Permissions 644 des fichiers portailxapi
  file:
    path: "{{ item.path }}"
    mode: '0644'
  loop: "{{ files_to_chmod.files }}"

- name: Repertoire storage accessible en ecriture par apache
  file:
    path: "{{ apache_www_path }}/storage"
    state: directory
    owner: apache
    group: apache
    mode: '0775'
    recurse: true

- name: Repertoire bootstrap/cache accessible en ecriture par apache
  file:
    path: "{{ apache_www_path }}/bootstrap/cache"
    state: directory
    owner: apache
    group: apache
    mode: '0775'
    recurse: true

- name: Permission 664 laravel.log
  file:
    path: "{{ apache_www_path }}/storage/logs/laravel.log"
    state: touch
    owner: apache
    group: apache
    mode: '0664'
