## config repmgr.conf sur le standby

# sauvegarde du fichier repmgr.conf.bak
- name: Copie du fichier repmgr.conf en extension repmgr.conf.bak
  ansible.builtin.copy:
    src: /etc/repmgr/17/repmgr.conf
    dest: /etc/repmgr/17/repmgr.conf.bak
    remote_src: true
    owner: root
    group: root
    mode: '0644'     # (option plus stricte: owner: root, group: postgres, mode: '0640')
  become: true

# configuration du fichier repmgr.conf
- name: Déploiement configuration repmgr.conf
  ansible.builtin.template:
    src: templates/repmgr.conf.j2
    dest: /etc/repmgr/17/repmgr.conf
    owner: root
    group: root
    mode: '0644'     # ou '0640' avec group: postgres si tu veux restreindre
  become: true

# redémarrer postgresql-17
- name: Redémarrer le service PostgreSQL 17
  ansible.builtin.systemd:
    name: postgresql-17
    state: restarted
  become: true
