galaxy_info:
  author: Move2Cloud
  company: ""
  license: ""
  min_ansible_version: "2.12"
  role_name: api_obs
  description: Déploie une API Observabilité sur serveur web
  platforms:
    - name: EL
      versions:
        - "8"
  galaxy_tags:
    - health
    - api
