---
- name: S'assurer que les dépendances de base sont installées
  ansible.builtin.package:
    name:
      - curl
      - policycoreutils-python-utils
      - libselinux-utils
    state: present

- name: Installer Elasticsearch (RPM local)
  ansible.builtin.yum:
    name: "kibana"
    state: present
