# configuration du service check_postgres.service
- name: Déploiement service check_postgres.service
  template:
    src: templates/check_postgres.service.j2
    dest: /etc/systemd/system/check_postgres.service
    owner: root
    group: root
    mode: '644'

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
- name: Enable and start check_postgres service
  ansible.builtin.systemd:
    name: check_postgres.service
    enabled: true
    state: started
