---
# Installe la commande unzip
- name: Install unzip
  ansible.builtin.package:
    name: unzip
    state: present

- name: Download archive, unzip it then removes it
  block:
    # Télécharge l'archive de l'application
    - name: Get API health archive
      ansible.builtin.get_url:
        url: "{{ api_obs_health_archive_url }}"
        url_username: "{{ api_obs_health_artifactory_username }}"
        url_password: "{{ api_obs_health_artifactory_password }}"
        dest: "{{ api_obs_archive_path }}"
        owner: "{{ api_obs_application_owner }}"
        group: "{{ api_obs_application_owner }}"
        mode: "0755"

    # Décompresse l'archive
    - name: Deploy API
      ansible.builtin.unarchive:
        remote_src: true
        src: "{{ api_obs_archive_path }}"
        dest: "{{ api_obs_website_main_path }}"

    - name: Create API folder and set rights
      ansible.builtin.file:
        path: "{{ api_obs_health_path }}"
        state: directory
        group: "{{ api_obs_application_owner }}"
        owner: "{{ api_obs_application_owner }}"
        mode: "0755"
        recurse: true
      become: true

  always:
    - name: Remove downloaded file
      ansible.builtin.file:
        path: "{{ api_obs_archive_path }}"
        state: absent
