---
# vérifie que les variables de configuration sont définies
- name: Verify that configuration variables are defined
  ansible.builtin.include_tasks: check_configuration_variables.yml
  run_once: true

# va chercher les fichiers de l'API, et les déploie sur l'hôte
- name: Deploy API files
  ansible.builtin.include_tasks: deploy_api.yml

# peuple les fichiers de configuration de l'API avec les variables saisie par l'utilisateur
- name: Configure API
  ansible.builtin.include_tasks: configure_api.yml
