---

# Auth TRAX via Keycloak (OIDC)
oidc_provider: "keycloak"
client_id_mindefconnect_trax: "int-xapi-mn-intradef"
redirect_url_trax: "https://{{ alias_dns_trax }}.{{ zone_url }}/trax/extended/auth/keycloak/callback"
backend_logout_url_trax: "https://{{ alias_dns_trax }}.{{ zone_url }}/trax/extended/auth/login"

#######################################################################
#                       Variables api obs                              #
#######################################################################

## Api observabilité
nom: "XAPI_MN"
trigramme: "XPN"
version: "1.0.0"
date_version: "2025-11-18T00:00:00Z"
environnement: "developpement"
classification_max_donnees: "DR"
mentions:
  - CP
niveau_arr: "I3"
niveau_service: "VPS"
direction_systeme_information: "PFM"
direction_application: "EMM/DPM/FORM/PPM"
type_homologation: "DEF"
date_fin_homologation: "2028-04-03T00:00:00Z"
date_fin_hebergement: "2035-01-01T00:00:00Z"

services_api_obs:
  sgbdr:
    - url: "http://{{ hostvars[groups['postgresql_primary'][0]].ansible_host }}"
      nom: 'postgres primary'
      port: '5432'
    - url: "http://{{ hostvars[groups['postgresql_replica'][0]].ansible_host }}"
      nom: 'postgres standby'
      port: '5432'

  nosql:
    - url: "https://{{ hostvars[groups['node1'][0]].ansible_host }}"
      nom: "elastic node1"
      port: "9200"
    - url: "https://{{ hostvars[groups['node2'][0]].ansible_host }}"
      nom: "elastic node2"
      port: "9200"
    - url: "https://{{ hostvars[groups['node3'][0]].ansible_host }}"
      nom: "elastic node3"
      port: "9200"
    - url: "https://{{ hostvars[groups['kibana'][0]].ansible_host }}"
      nom: "kibana"
      port: "443"

  passerelle:
    - url: "http://{{ hostvars[groups['loadbalancer'][0]].ansible_host }}"
      nom: "haproxy"
      port: "8404"
    - url: "http://{{ hostvars[groups['loadbalancer'][0]].ansible_host }}"
      nom: "haproxy postgres frontend"
      port: "5432"
    - url: "http://{{ hostvars[groups['loadbalancer'][0]].ansible_host }}"
      nom: "haproxy check_postgres handler"
      port: "9200"
    - url: "https://{{ alias_dns_portailxapi }}.{{ zone_url }}"
      nom: "PortailXapi"
      port: "443"

  authentification:
    - url: "{{ oidc_issuer_url }}"
      nom: 'MindefConnect'
      port: '443'

api_service_url_si: "https://{{ alias_dns_trax }}.{{ zone_url }}"

# Repository_downloads_path_for_api_observability: 'https://medusa.picsel.defense.gouv.fr:443/artifactory/commun-generic/download/health/'
# Lien vers une version de l'api_health corrigé par PPM (affichage de la categorie passerelle)
# repository_downloads_path_for_api_observability: 'https://medusa.picsel.defense.gouv.fr:443/artifactory/zpn_xapi_mn-generic/api_health'
repository_downloads_path_for_api_observability: "{{ artifactory_depot_generic }}/api_health"

# Alias obs health et info
api_obs_health_alias_url: "/v1/api/observability/health"
api_obs_info_alias_url: "/v1/api/observability/info"
