---

#####################################################################
# Suppression des données temporaires placées dans /tmp
#####################################################################

- name: Supprimer les datas temporaires dans /tmp
  ansible.builtin.file:
    path: "{{ vm_file_path }}{{ item }}"
    state: absent

  loop:
    # CA Elasticsearch
    - "{{ ca_elastic }}"

    # oauth2-proxy
    - "{{ oauth2_tar }}"
    - "{{ oauth2_tar }}{{ oauth2_extension }}"
