---

## Task de suppression des cert et trax3 placés dans /tmp

- name: Supprimer les certificats temporaires dans /tmp
  ansible.builtin.file:
    path: "{{ vm_file_path }}{{ item }}"
    state: absent
  loop:
    - "{{ server_apache_crt }}"
    - "{{ server_apache_key }}"
    - "{{ ca_front_xapi }}"
    - "{{ ca_chain_xapi }}"
    - "{{ trax_package }}"
    - "{{ ca_elastic }}"
