---

## copier le rpm repmgr repmgr de medusa dans fichier /tmp
- name: Récupération du fichier repmgr_17-5.5.0-1PGDG.rhel8.x86_64.rpm et dépôt sur la VM
  minarm.core.adaptable.get_url:
    url: "atf://{{ repmgr_file_path }}"
    dest: "{{ vm_file_path }}"
    url_category: "livrable"
    username: "{{ artifactory_user }}"
    password: "{{ artifactory_password }}"

## installer localement repmgr
- name: Ensure the RPM package is installed
  yum:
    name: "{{ vm_file_path }}{{ repmgr_package }}"
    state: present
    disable_gpg_check: true
## donner les droits d'execution du binaire repmgr
- name: Add PATH to /etc/profile
  lineinfile:
    path: /etc/profile
    line: 'export PATH=$PATH:/usr/pgsql-17/bin'
    state: present

- name: Create repmgr.sh in /etc/profile.d
  copy:
    dest: /etc/profile.d/repmgr.sh
    content: |
      export PATH=$PATH:/usr/pgsql-17/bin
    mode: '0644'

- name: Afficher le PATH (shell de login, pas de changement)
  ansible.builtin.shell: bash -lc 'echo "$PATH"'
  args:
    executable: /bin/bash
  register: path_output
  changed_when: false

- name: Debug PATH
  ansible.builtin.debug:
    var: path_output.stdout


- name: Verify PATH is updated in the current shell
  assert:
    that:
      - "'/usr/pgsql-17/bin' in path_output.stdout"
    fail_msg: "The PATH was not updated correctly."
