- name: Reload systemd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart oauth2-proxy
  become: true
  ansible.builtin.service:
    name: oauth2-proxy
    state: restarted
    enabled: true

- name: Restart nginx
  become: true
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true
