---
- name: Stop HAProxy service
  service:
    name: haproxy
    state: stopped

- name: Generate HAProxy configuration file
  template:
    src: "{{ haproxy_config_template }}"
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'

- name: Restart HAProxy service
  service:
    name: haproxy
    state: restarted
