---
- name: Récupération du fichier oauth2-proxy dépôt sur la VM dans /tmp/
  minarm.core.adaptable.get_url:
    url: "atf://{{ oauth2_medusa_file_path }}"
    dest: "{{ vm_file_path }}"
    url_category: "livrable"
    username: "{{ artifactory_user }}"
    password: "{{ artifactory_password }}"

- name: Extraire oauth2-proxy archive dans /tmp
  ansible.builtin.unarchive:
    src: "{{ vm_file_path }}{{ oauth2_tar }}{{ oauth2_extension }}"
    dest: "{{ vm_file_path }}"
    remote_src: true
    creates: "{{ vm_file_path }}{{ oauth2_tar }}"

- name: Configurer utilisateur système oauth2-proxy et les répertoires
  become: true
  block:
    - name: Ensure oauth2-proxy directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop:
        - "{{ path_binaire_oauth2 }}"
        - "{{ path_oauth2 }}"

    - name: Vérifier que utilisateur système oauth2-proxy existe
      ansible.builtin.user:
        name: oauth2-proxy
        system: true
        home: "{{ path_binaire_oauth2 }}"
        shell: /sbin/nologin
        create_home: false
        state: present

- name: Installer le binaire oauth2-proxy dans /opt/oauth2-proxy
  become: true
  block:
    - name: Copy oauth2-proxy binary to /opt/oauth2-proxy
      ansible.builtin.copy:
        src: "{{ vm_file_path }}{{ oauth2_tar }}/{{ owner_oauth2 }}"
        dest: "{{ path_binaire_oauth2 }}/{{ owner_oauth2 }}"
        owner: "{{ owner_oauth2 }}"
        group: "{{ group_oauth2 }}"
        mode: '0755'
        remote_src: true

    - name: Vérifier que le répertoire /opt/oauth2-proxy appartient à utilisateur oauth2-proxy
      ansible.builtin.file:
        path: "{{ path_binaire_oauth2 }}"
        owner: "{{ owner_oauth2 }}"
        group: "{{ group_oauth2 }}"
        recurse: true
