---

## Task de suppression des data placés dans /tmp

- name: Supprimer des datas temporaires dans /tmp
  ansible.builtin.file:
    path: "{{ vm_file_path }}{{ item }}"
    state: absent
  loop:
    - "{{ ca_chain_xapi }}"
    - "{{ ca_portailxapi }}"
    - "{{ server_apache_portailxapi_crt }}"
    - "{{ server_apache_portailxapi_key }}"
    - "{{ portailxapi_package }}"
