# HTTP -> HTTPS redirect
server {
    listen 80;
    server_name {{ alias_dns_kibana }}.{{ zone_url }};

    return 301 https://$host$request_uri;
}

# HTTPS termination + reverse proxy to Kibana (WebSocket-ready)
server {
    listen 443 ssl;
    http2 on;
    server_name {{ alias_dns_kibana }}.{{ zone_url }};

    # --- TLS ---
    ssl_certificate     {{ kibana_cert_path }};
    ssl_certificate_key {{ kibana_key_path }};

    # (Optionnel) Renforce TLS
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;
    ssl_session_tickets off;

    # HSTS (décommente si certs OK partout)
    # add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;

    # --- Proxy vers Kibana ---
    location / {
        proxy_pass {{ kibana_backend_url }};
        proxy_http_version 1.1;

        # WebSocket
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # En-têtes utiles
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # TLS côté backend Kibana
        proxy_ssl_server_name on;
        proxy_ssl_verify off;   # (rapide) -> on pourra remettre "on" avec la CA ci-dessous
        #proxy_ssl_trusted_certificate <path certificat IGC>;

        # Timeouts/buffers (Kibana peut faire des requêtes longues)
        proxy_read_timeout  900s;
        proxy_send_timeout  900s;
        proxy_connect_timeout 60s;

        # Si besoin (payload volumineux)
        # client_max_body_size 50m;
    }

    # (Optionnel) Santé basique
    location = /health {
        return 200 'ok';
        add_header Content-Type text/plain;
    }

    # (Optionnel) Accès aux logs spécifiques
    access_log /var/log/nginx/kibana.access.log;
    error_log  /var/log/nginx/kibana.error.log warn;
}
