---
- name: Ensure oauth2-proxy directory ownership and permissions
  ansible.builtin.file:
    path: /etc/oauth2-proxy
    state: directory
    owner: "{{ owner_oauth2 }}"
    group: "{{ group_oauth2 }}"
    mode: '0750'
    recurse: true

- name: Deploy oauth2-proxy configuration file
  become: true
  ansible.builtin.template:
    src: templates/oauth2-proxy.cfg.j2
    dest: "{{ path_oauth2_config }}"
    owner: "{{ owner_oauth2 }}"
    group: "{{ group_oauth2 }}"
    mode: '0640'

- name: Deploy oauth2-proxy systemd unit file
  become: true
  ansible.builtin.template:
    src: templates/oauth2-proxy.service.j2
    dest: "{{ path_oauth2_service }}"
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload systemd

- name: Générer la chaîne Basic Auth pour Kibana
  set_fact:
    kibana_proxy_basic: "{{ (vars['user_kibana_proxy'] ~ ':' ~ kibana_proxy_password) | b64encode }}"
    kibana_proxy_auth_header: "Basic {{ (vars['user_kibana_proxy'] ~ ':' ~ kibana_proxy_password) | b64encode }}"
  no_log: true

# - name: Afficher la chaine basic
#   debug:
#     msg: "Chaîne basic = {{ kibana_proxy_basic }}"

- name: Deploy NGINX configuration file
  become: true
  ansible.builtin.template:
    src: templates/kibana.cfg.j2
    dest: "{{ path_nginx_kibana_config }}"
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart nginx
    - Restart oauth2-proxy
