---
- name: Get secrets from GDS
  hosts: all
  become: true
  collections:
    - minarm.gds
  roles:
    - role: vault_manage_secret
  vars:
    vault_action: get
    vault_secret_dict: "{{ gds_secret }}"
...
