---
- name: Gather facts
  hosts: all
  gather_facts: true
  tasks: []

- name: Install oauth2-proxy
  hosts: kibana
  become: true
  environment:
    MINARM_ATF_REPO_LIVRABLE_BASEURL: "{{ medusa_url }}"
  collections:
    - minarm.gds
  roles:
    - role: oauth2_medusa
    - role: oauth2_config
    - role: oauth2_create_user
    - role: clean_tmp_srv_kibana
