---

- name: Test playbook
  hosts: postgresql_primary
  gather_facts: true
  become: true
  collections:
    - minarm.gds

  tasks:
    - name: Afficher la valeur de la variable
      debug:
        msg: |
          "La valeur 2 {{ si_gds }} : {{ obs_postgresql_password }}"
          "La valeur 3 {{ si_gds }} : {{ postgresql_unix_account_password }}"
          "La valeur 4 {{ si_gds }} : {{ postgresql_db_account_password }}"

    - name: Test de connectivité Ansible (ping)
      ansible.builtin.ping:

    - name: Afficher quelques infos système
      ansible.builtin.debug:
        msg:
          - "Host: {{ inventory_hostname }}"
          - "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"
          - "Kernel: {{ ansible_kernel }}"
          - "IP: {{ ansible_default_ipv4.address | default('N/A') }}"
