- name: Récupérer les certificats postgres pg1 de medusa et copie dans /tmp
  minarm.core.adaptable.get_url:
    url: "atf://{{ item.path }}"
    dest: "{{ vm_file_path }}"
    url_category: "livrable"
    username: "{{ artifactory_user }}"
    password: "{{ artifactory_password }}"
  loop:
    - { path: "{{ ca_chain_xapi_file_path }}" }
    - { path: "{{ server_pg1_key_file_path }}" }
    - { path: "{{ server_pg1_crt_file_path }}" }
