---
all:
  children:
    database:
      hosts:
        db1:
          ansible_host: XAPIPG1INT231V.picsel.defense.gouv.fr
        db2:
          ansible_host: XAPIPG2INT380V.picsel.defense.gouv.fr

    front:
      hosts:
        web:
          ansible_host: XAPIWEBINT829V.picsel.defense.gouv.fr

    portailxapi:
      hosts:
        portail:
          ansible_host: XAPISITEINT893V.picsel.defense.gouv.fr

    loadbalancer:
      hosts:
        haproxy:
          ansible_host: XAPIHAPINT185V.picsel.defense.gouv.fr

    postgresql:
      children:
        postgresql_primary:
          hosts:
            db1:
        postgresql_replica:
          hosts:
            db2:

    elasticsearch_cluster:
      children:
        node1:
          hosts:
            es1:
              ansible_host: XAPIES1INT445V.picsel.defense.gouv.fr
              es_node_key: node1
        node2:
          hosts:
            es2:
              ansible_host: XAPIES2INT443V.picsel.defense.gouv.fr
              es_node_key: node2
        node3:
          hosts:
            es3:
              ansible_host: XAPIES3INT278V.picsel.defense.gouv.fr
              es_node_key: node3

    kibana:
      hosts:
        kib1:
          ansible_host: XAPIKIBINT058V.picsel.defense.gouv.fr
    oauth2:
      hosts:
        kib1:
          ansible_host: XAPIKIBINT058V.picsel.defense.gouv.fr # Oauth2 deployé sur vm Kibana

# VMs dédiées aux services de supervision
    heartbeat:
      hosts:
        obs1:
          ansible_host: XAPIOBSINT547V.picsel.defense.gouv.fr
    logstash:
      hosts:
        obs1:
          ansible_host: XAPIOBSINT547V.picsel.defense.gouv.fr
    otelcol:
      hosts:
        obs1:
          ansible_host: XAPIOBSINT547V.picsel.defense.gouv.fr
